# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #Use a Ubuntu 14.04 base
  config.vm.box = "ubuntu/trusty64"
  #Use a Ubuntu 16.04 base
  #config.vm.box = "ubuntu/xenial64"

  # Share an additional folder to the guest VM. 
  config.vm.synced_folder "C:/C_Sandboxes", "/C_Sandboxes"

  # Provider-specific configuration 
  config.vm.provider "virtualbox" do |vb|
	vb.name = "DevEnv"
 	vb.memory = "4096"
  end
  
  # Enable provisioning with a shell script. 
   config.vm.provision "shell", privileged: false, inline: <<-SHELL
  	sudo apt-get install -y git
	git clone https://github.com/caanaan/linuxdevconfig.git ~/.myconfig
	echo "NOTE - you will need to run the ~/.myconfig/installAll.sh script to set up everything!"
	echo " This WILL take a while!"
   SHELL
end
