# Load Anitgen - the zsh package manager
#  * Requires the following installed: Zsh, Git, tmux, and Oh-my-zsh.
#   - sudo apt-get install zsh
#   - sudo apt-get install git-core
#   - sudo apt-get install tmux
#   - sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
#  * Antigen must be installed first. 
#   - cd ~/.zsh
#   - git clone https://github.com/zsh-users/antigen.git
source ~/.antigen/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle git-flow
antigen bundle pip
antigen bundle command-not-found
antigen bundle autojump
antigen bundle common-aliases
antigen bundle dirhistory
antigen bundle docker
antigen bundle fasd
antigen bundle python
antigen bundle sudo
antigen bundle rake
antigen bundle rsync
antigen bundle history
antigen bundle tmux
antigen bundle autopep8
antigen bundle httpie
antigen bundle pip
antigen bundle vagrant

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Autosuggestions
antigen bundle tarruda/zsh-autosuggestions

# Other zsh plugins
antigen bundle djui/alias-tips
antigen bundle voronkovich/gitignore.plugin.zsh
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions src
antigen bundle srijanshetty/zsh-pandoc-completion
antigen bundle srijanshetty/zsh-pip-completion
antigen bundle jreese/zsh-titles
#antigen bundle nojhan/liquidprompt #Auto-changing prompt.  Cool need to evaluate.
#antigen bundle skx/sysadmin-util #Note sure this is needed
#antigen bundle b4b4r07/enhancd #Need to get fzf working, then try

# Set personal aliases
alias zshconfig="vim ~/.myconfig/zsh/zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias zshsource="source ~/.zshrc"
alias vimconfig="vim ~/.myconfig/vim/vimrc"
alias tmuxconfig="vim ~/.myconfig/zsh/tmux.conf"
alias tmuxsource='tmux source ~/.tmux.conf'
alias kvm="kvmswitch.sh"
alias myconfigcd="cd ~/.myconfig"
alias pubkey="xclip -sel clip < ~/.ssh/id_rsa.pub; printf '=> Public key copied to pasteboard.\n'";
alias gitlog="git log --graph --oneline --pretty --decorate --all"
alias csetup="ctags -R .; cscope -R -b"
alias git_creds="git config --global credential.helper 'cache --timeout=3600'"
alias git_dirty_hide="git config --add oh-my-zsh.hide-dirty 1"
alias git_dirty_display="git config --add oh-my-zsh.hide-dirty 0"
alias git_status_speedup="git config core.preloadindex true; git gc"
#Git status with no searching for untracked files
alias gstu="git status -uno"

#Android environmental variables
export ANDROID_HOME=~/Android/Sdk
export PATH=${PATH}:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools

#Go stuff
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/Sandboxes/Go

# Load the theme.
#antigen theme skaro
antigen theme lukes-dev-theme

# Tell antigen that you're done.
antigen apply

# Other settings
# if you do a 'rm *', Zsh will give you a sanity check!
setopt RM_STAR_WAIT
# allows you to type Bash style comments on your command line
# good 'ol Bash
setopt interactivecomments
#Set the EDITOR
export EDITOR='vim'
# Set completion waiting dots
COMPLETION_WAITING_DOTS="true"

#Android Studio Stuff
#
export ANDROID_HOME=~/Android/Sdk
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export PATH=${PATH}:${ANDROID_HOME}/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${JAVA_HOME}/bin

#Terminal setup
#Turn off flow control
stty -ixon

if [ -e /usr/share/terminfo/x/xterm-256color ]; then
        export TERM='xterm-256color'
else
        export TERM='xterm-color'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
